### ISSUE TITLE
FIND seems to trigger a full resync

### ISSUE THREAD

**Issue by amaccuish** [grommunio/grommunio-sync#13]
Grommunio-Sync has become a lot more reliable, thank you for your work!

Whilst the resyncs with this problematic user have become a lot better, they still remain. The only thing I can see is that they often occur after the iPad issues a FIND command.

> 01/04/2023 11:24:34 [11718] [DEBUG] GSync::CommandNeedsPlainInput(23): false
01/04/2023 11:24:34 [11718] [WBXML] I  <Find:Find>
01/04/2023 11:24:34 [11718] [WBXML] I   <Find:SearchId>
01/04/2023 11:24:34 [11718] [WBXML] I    DD721BE0-C232-4CD8-A32B-5850163F3B1F
01/04/2023 11:24:34 [11718] [WBXML] I   </Find:SearchId>
01/04/2023 11:24:34 [11718] [WBXML] I   <Find:ExecuteSearch>
01/04/2023 11:24:34 [11718] [WBXML] I    <Find:MailBoxSearchCriterion>
01/04/2023 11:24:34 [11718] [WBXML] I     <Find:Query>
01/04/2023 11:24:34 [11718] [WBXML] I      <FolderType>
01/04/2023 11:24:34 [11718] [WBXML] I       Email
01/04/2023 11:24:34 [11718] [WBXML] I      </FolderType>
01/04/2023 11:24:34 [11718] [WBXML] I      <Find:FreeText>
01/04/2023 11:24:34 [11718] [WBXML] I       from:"Stoneacre Motor Group"
01/04/2023 11:24:34 [11718] [WBXML] I      </Find:FreeText>
01/04/2023 11:24:34 [11718] [WBXML] I     </Find:Query>
01/04/2023 11:24:34 [11718] [WBXML] I     <Find:Options>
01/04/2023 11:24:34 [11718] [WBXML] I      <Find:Range>
01/04/2023 11:24:34 [11718] [WBXML] I       0-99
01/04/2023 11:24:34 [11718] [WBXML] I      </Find:Range>
01/04/2023 11:24:34 [11718] [WBXML] I     </Find:Options>
01/04/2023 11:24:34 [11718] [WBXML] I    </Find:MailBoxSearchCriterion>
01/04/2023 11:24:34 [11718] [WBXML] I   </Find:ExecuteSearch>
01/04/2023 11:24:34 [11718] [WBXML] I  </Find:Find>
01/04/2023 11:24:34 [11718] [DEBUG] WBXMLEncoder->startWBXML() type: vnd.ms-sync.wbxml
01/04/2023 11:24:34 [11718] [WBXML] O  <Find:Find>
01/04/2023 11:24:34 [11718] [WBXML] O   <Find:Status>
01/04/2023 11:24:34 [11718] [WBXML] O   1
01/04/2023 11:24:34 [11718] [WBXML] O   </Find:Status>
01/04/2023 11:24:34 [11718] [DEBUG] DeviceManager->GetBackendIdForFolderId(): no backend-folderid available for '', returning as is.
01/04/2023 11:24:34 [11718] [DEBUG] Grommunio->GetMailboxSearchResults(): Do FIND
01/04/2023 11:24:34 [11718] [DEBUG] Grommunio->getFindRestriction(): extracted words: Stoneacre Motor Group
01/04/2023 11:24:34 [11718] [WBXML] O   <Find:Response>
01/04/2023 11:24:34 [11718] [WBXML] O    <ItemOperations:Store>
01/04/2023 11:24:34 [11718] [WBXML] O    Mailbox
01/04/2023 11:24:34 [11718] [WBXML] O    </ItemOperations:Store>
01/04/2023 11:24:34 [11718] [WBXML] O    <Find:Status>
01/04/2023 11:24:34 [11718] [WBXML] O    1
01/04/2023 11:24:34 [11718] [WBXML] O    </Find:Status>
01/04/2023 11:24:34 [11718] [WBXML] O    <Find:Range>
01/04/2023 11:24:34 [11718] [WBXML] O    0-0
01/04/2023 11:24:34 [11718] [WBXML] O    </Find:Range>
01/04/2023 11:24:34 [11718] [WBXML] O   </Find:Response>
01/04/2023 11:24:34 [11718] [WBXML] O  </Find:Find>
01/04/2023 11:24:34 [11718] [DEBUG] WBXMLEncoder->endTag() WBXML output completed
01/04/2023 11:24:34 [11718] [WBXML] WBXML-OUT: AwFqAAAZRUoDMQABUQAURwNNYWlsYm94AAEAGUoDMQABTQMwLTAAAQEB
01/04/2023 11:24:34 [11718] [WBXML] WBXML-IN : AwFqAAAZRUYDREQ3MjFCRTAtQzIzMi00Q0Q4LUEzMkItNTg1MDE2M0YzQjFGAAFHSEkAAFADRW1haWwAAQAZSwNmcm9tOiJTdG9uZWFjcmUgTW90b3IgR3JvdXAiAAEBTE0DMC05OQABAQEBAQ==
01/04/2023 11:24:34 [11718] [DEBUG] LoopDetection->ProcessLoopDetectionTerminate()

and then

> 01/04/2023 11:24:39 [18105] [DEBUG] GSync::CommandNeedsPlainInput(0): false
01/04/2023 11:24:39 [18105] [WBXML] I  <Synchronize>
01/04/2023 11:24:39 [18105] [WBXML] I   <Folders>
01/04/2023 11:24:39 [18105] [WBXML] I    <Folder>
01/04/2023 11:24:39 [18105] [WBXML] I     <SyncKey>
01/04/2023 11:24:39 [18105] [WBXML] I      0
01/04/2023 11:24:39 [18105] [WBXML] I     </SyncKey>
01/04/2023 11:24:39 [18105] [WBXML] I     <FolderId>
01/04/2023 11:24:39 [18105] [WBXML] I      kDAMailAccountAllMailboxesFolderID
01/04/2023 11:24:39 [18105] [WBXML] I     </FolderId>
01/04/2023 11:24:39 [18105] [DEBUG] SyncParameters->RemoveSyncKey(): saved sync key removed
01/04/2023 11:24:39 [18105] [DEBUG] DeviceManager->GetBackendIdForFolderId(): no backend-folderid available for 'kDAMailAccountAllMailboxesFolderID', returning as is.
01/04/2023 11:24:39 [18105] [INFO] NoHierarchyCacheAvailableException: Folderid 'kDAMailAccountAllMailboxesFolderID' is not fully synchronized on the device - code: 0 - file: /usr/share/grommunio-sync/lib/core/devicemanag>
01/04/2023 11:24:39 [18105] [INFO] Full device resync requested

I've included a more detailed log attached.

[7ag2cupohh64dfksh0chk10dtg.log](https://github.com/grommunio/grommunio-sync/files/11132681/7ag2cupohh64dfksh0chk10dtg.log)

**Comment by gromandreas** [comment]
Hi @amaccuish ,

is the folder's id really ` kDAMailAccountAllMailboxesFolderID` or did you replace its id? It is strange that this folder doesn't appear in the folder list during the `FolderSync` command.

Do you have multiple ActiveSync/Exchange accounts configured on your iPad? Are there another clients connected to this account (Outlook, Thunderbird, another mobile device...)?

**Comment by amaccuish** [comment]
@gromandreas hi!

on the iPad there are no other accounts configured. I did not replace this folder, and it doesn't exist in the account. It always seems to be requested when the resync happens, I'm pretty sure the log file in the other ticket has it too.

**Comment by gromandreas** [comment]
Did you try to remove the account on the device or do the full resync in order to check if that folder disappears?

**Comment by amaccuish** [comment]
The folder doesn't exist. But yes a full resync and removing and readding have been tried.
![photo_2023-04-12_19-54-36](https://user-images.githubusercontent.com/9434795/231543297-3bbcfc07-7cb3-4664-b686-3142eef62590.jpg)

**Comment by amaccuish** [comment]
Should I try and create the folder and see what happens? Is there a way to make the folder hidden in the web ui?

**Comment by amaccuish** [comment]
@gromandreas It's the default/built-in client, no other apps.

I have been trying to reproduce, I use an iPhone, but can't make it happen on my own device.

However, fairly reliably we can trigger it by doing a search. Here is one from just now. Apparently they're just doing a normal search. I will keep trying to see if I can reproduce, and also if it's possible to get a video/screen capture.

[Untitled-1.log](https://github.com/grommunio/grommunio-sync/files/11225180/Untitled-1.log)

**Comment by gromandreas** [comment]
@amaccuish yes, it would be great if you would provide a video/screen capture. Are they doing the search directly from the inbox? Or from one of those special Mailboxes (VIP, Flagged, Unread)?
