### ISSUE TITLE
select or automaticly publishing public folder 

### ISSUE THREAD

**Issue by HumphRey123** [grommunio/grommunio-sync#2]
H i there,
https://community.grommunio.com/d/581-grommunio-sync-und-publicfolder

that would be very nice to implement this feature. 
either by script or preferably by AdminUI .

**Comment by grammmike** [comment]
@HumphRey123,

now available with:

https://github.com/grommunio/grommunio-sync/commit/8c95d311a2dd9dd1f2b1b07e804d6c46a9ac06f8
https://github.com/grommunio/admin-api/commit/89f27447e39b42e06602f145ccfd841f2079e96b
https://github.com/grommunio/admin-web/commit/85c66182a192c3f87ee77af02727f9b196bd439b

you can now define in the public folder area in admin ui which public folders should be pushed to mobiles. be careful, depending on your size of installation, this might create quite some load. in admin ui there is an extra hint to `one does not just simply` enabled it without thought.
