### ISSUE TITLE
Uncaught TypeError: mapi_setprops(): Argument #1 ($any) must be of type resource, bool given

### ISSUE THREAD

**Issue by amaccuish** [grommunio/grommunio-sync#7]
Let me know if you need wbxml logs :)

> 01/02/2023 19:52:43 [25040] [ WARN] [xxx@xxx.xxx.xxx] StatusException: ExportChangesICS->GetState(): Error, state not available or unable to update: 0x4B9 - code: 12 - file: /usr/share/grommunio-sync/lib/grommunio/exporter.php:254
> 01/02/2023 19:52:43 [25040] [ERROR] [xxx@xxx.xxx.xxx] HandleSync(): error saving '{89a611b6-47ed-4e89-92d1-a480e095a3c2}696' - no state information available
> 01/02/2023 19:58:52 [26182] [ WARN] [xxx@xxx.xxx.xxx] StatusException: ExportChangesICS->InitializeExporter(): Error, mapi_exportchanges_config() failed: 0x80004005 - code: 12 - file: /usr/share/grommunio-sync/lib/grommunio/exporter.php:216
> 01/02/2023 20:39:00 [27062] [ WARN] [xxx@xxx.xxx.xxx] SyncObjectBrokenException: The message doesn't have a sourcekey - code: 0 - file: /usr/share/grommunio-sync/lib/grommunio/mapiprovider.php:618
> 01/02/2023 20:39:00 [27062] [ERROR] [xxx@xxx.xxx.xxx] PHPWrapper->ImportMessageChange(): Caught SyncObjectBrokenException but no ID of object set
> 01/02/2023 20:39:00 [27062] [ERROR] [xxx@xxx.xxx.xxx] Ignored broken message (SyncMail). Reason: '1' Folderid: 'Uaed3e' message id 'Unknown ID'
> 01/02/2023 20:39:00 [27062] [FATAL] [xxx@xxx.xxx.xxx] Fatal error: /usr/share/grommunio-sync/lib/grommunio/grommunio.php:1983 - Uncaught TypeError: mapi_setprops(): Argument #1 ($any) must be of type resource, bool given in /usr/share/grommunio-sync/lib/grommunio/grommunio.php:1983
> Stack trace:
> #0 /usr/share/grommunio-sync/lib/grommunio/grommunio.php(1983): mapi_setprops(false, Array)
> #1 /usr/share/grommunio-sync/lib/grommunio/grommunio.php(1727): Grommunio->setStateMessage('\x04\x00\x02\x01\x17@\x84\x01\x01\x00\x04\x00\x00\x00\x03...', '7ag2cupohh64dfk...', '', 'eeada295-1660-4...', 411)
> #2 /usr/share/grommunio-sync/lib/core/statemanager.php(219): Grommunio->SetState('\x04\x00\x02\x01\x17@\x84\x01\x01\x00\x04\x00\x00\x00\x03...', '7ag2cupohh64dfk...', '', 'eeada295-1660-4...', 411)
> #3 /usr/share/grommunio-sync/lib/request/sync.php(1325): StateManager->SetSyncState('{eeada295-1660-...', '\x04\x00\x02\x01\x17@\x84\x01\x01\x00\x04\x00\x00\x00\x03...', 'Uaed3e')
> #4 /usr/share/grommunio-sync/lib/request/sync.php(965): Sync->syncFolder(Object(SyncCollections), Object(SyncParameters), Object(ExportChangesICS), 36394, Object(ImportChangesStream), 1, '1675280042/4661...')
> #5 /usr/share/grommunio-sync/lib/request/requestprocessor.php(98): Sync->Handle(0)
> #6 /usr/share/grommunio-sync/index.php(114): RequestProcessor::HandleRequest()
> #7 {main}
>   thrown (1)
>

**Comment by amaccuish** [comment]
Closed as seems to be related to midb restarting, sorry again!

**Comment by jengelh** [comment]
midb is not exercised by php_mapi/g-web/g-sync.

**Comment by amaccuish** [comment]
Ahh understood, zcore restarted at the same time too.
