### ISSUE TITLE
Can't send email from Windows Mail

### ISSUE THREAD

**Issue by amaccuish** [grommunio/grommunio-sync#9]
> 06/02/2023 19:29:48 [28007] [DEBUG] -------- Start
> 06/02/2023 19:29:48 [28007] [DEBUG] cmd='SendMail' devType='WindowsMail' devId='7b26cc46506e17cd9a5aadd2b0fb620b' getUser='robin@xxx.xxx.xxx' from='2407:7000:a19b:bd00:7416:db19:87b7:482' version='1.1.62' method='POST'
> 06/02/2023 19:29:48 [28007] [DEBUG] Used timezone 'Europe/Vienna'
> 06/02/2023 19:29:48 [28007] [DEBUG] Grommunio using PHP-MAPI version: 2.3.0.de34c2d - PHP version: 8.0.27
> 06/02/2023 19:29:48 [28007] [DEBUG] Request::ProcessHeaders(): base64 query string: 'jQEJDBB7JsxGUG4XzZpardKw+2ILBAFD7xMLV2luZG93c01haWw=' (decoded: 'ProtVer=141,Command=1,Locale=3081,DevIDLen=16,DevID=7b26cc46506e17cd9a5aadd2b0fb620b,PolKeyLen=4,PolKey=334447361,DevTypeLen=11,DevType=WindowsMail')
> 06/02/2023 19:29:48 [28007] [DEBUG] Request::ProcessHeaders() ASVersion: 14.1
> 06/02/2023 19:29:48 [28007] [DEBUG] GSync::CommandNeedsProvisioning(1): true
> 06/02/2023 19:29:48 [28007] [DEBUG] ProvisioningManager->ProvisioningRequired('334447361') saved device key '334447361': false
> 06/02/2023 19:29:48 [28007] [DEBUG] ProvisioningManager->ProvisioningRequired() saved policy hash '16e9d28d8d85649de7b4deb661ba5dc2' matches
> 06/02/2023 19:29:48 [28007] [DEBUG] GSync::CommandNeedsAuthentication(1): true
> 06/02/2023 19:29:48 [28007] [DEBUG] Grommunio->Logon(): Trying to authenticate user 'robin@xxx.xxx.xxx'..
> 06/02/2023 19:29:48 [28007] [DEBUG] Grommunio->openMessageStore('robin@xxx.xxx.xxx'): Found 'DEFAULT' store: 'Resource id #9'
> 06/02/2023 19:29:48 [28007] [DEBUG] Grommunio->Logon(): User 'robin@xxx.xxx.xxx' is authenticated
> 06/02/2023 19:29:48 [28007] [DEBUG] Store supports properties containing Unicode characters.
> 06/02/2023 19:29:48 [28007] [DEBUG] GSync::HierarchyCommand(1): false
> 06/02/2023 19:29:48 [28007] [DEBUG] GSync::CommandNeedsPlainInput(1): false
> 06/02/2023 19:29:48 [28007] [WBXML] I  <ComposeMail:SendMail>
> 06/02/2023 19:29:48 [28007] [WBXML] I   <ComposeMail:SaveInSentItems/>
> 06/02/2023 19:29:48 [28007] [WBXML] I   <ComposeMail:ClientId>
> 06/02/2023 19:29:48 [28007] [WBXML] I    oid{15aed:72}
> 06/02/2023 19:29:48 [28007] [WBXML] I   </ComposeMail:ClientId>
> 06/02/2023 19:29:48 [28007] [WBXML] I   <ComposeMail:MIME>
> 06/02/2023 19:29:48 [28007] [WBXML] I    MIME-Version: 1.0
> To: Andrew XXX <andrew@xxx.xxx.xxx>,
>         Alex XXX <alex@xxx.xxx.xxx>
> From:
> Subject: RE: Here w go
> Date: Tue, 7 Feb 2023 07:29:48 +1300
> Importance: normal
> X-Priority: 3
> content-class: urn:content-classes:message
> Thread-Topic:
> Content-Transfer-Encoding: quoted-printable
> Content-Type: text/plain; charset="utf-8"
> 
> test
> 
> Sent from Mail for Windows
> 
> From: Andrew XXX
> Sent: Tuesday, 7 February 2023 6:47 AM
> To: Alex XXX
> Cc: Robin XXX
> Subject: Re: Here w go
> 
> I assume grandma can now both send and receive emails?Sent from my iPadOn 6=
>  Feb 2023, at 17:45, Alex XXX alex@xxx.xxx.xxx wrote:=EF=BB=BFAlso=
>  received!Von meinem iPhone gesendetAm 06.02.2023 um 18:45 schrieb Robin Ma=
> cCuish robin@xxx.xxx.xxx:=EF=BB=BF=C2=A0=C2=A0Sent from Mail for Window=
> s=C2=A0=
> 
> 06/02/2023 19:29:48 [28007] [WBXML] I   </ComposeMail:MIME>
> 06/02/2023 19:29:48 [28007] [WBXML] I  </ComposeMail:SendMail>
> 06/02/2023 19:29:48 [28007] [DEBUG] Grommunio->SendMail(): RFC822: 848 bytes  forward-id: 'null' reply-id: 'null' parent-id: 'false' SaveInSent: '1' ReplaceMIME: 'false'
> 06/02/2023 19:29:48 [28007] [DEBUG] Grommunio->SendMail(): Use the mapi_inetmapi_imtomapi function
> 06/02/2023 19:29:48 [28007] [INFO] StatusException: Grommunio->SendMail(): Error saving/submitting the message to the Outbox: 0x80070005 - code: 120 - file: /usr/share/grommunio-sync/lib/grommunio/grommunio.php:636
> 06/02/2023 19:29:48 [28007] [DEBUG] WBXMLEncoder->startWBXML() type: vnd.ms-sync.wbxml
> 06/02/2023 19:29:48 [28007] [WBXML] O  <ComposeMail:SendMail>
> 06/02/2023 19:29:48 [28007] [WBXML] O   <ComposeMail:Status>
> 06/02/2023 19:29:48 [28007] [WBXML] O   120
> 06/02/2023 19:29:48 [28007] [WBXML] O   </ComposeMail:Status>
> 06/02/2023 19:29:48 [28007] [WBXML] O  </ComposeMail:SendMail>
> 06/02/2023 19:29:48 [28007] [DEBUG] WBXMLEncoder->endTag() WBXML output completed

During this time, these messages can be seen from zcore

> Feb 06 19:36:10 mx01 zcore[28204]: ZRPC FAIL 80070005h  3443µs SUBMITMESSAGE
Feb 06 19:36:11 mx01 zcore[28204]: I-1334: uid robin@xxx.xxx.xxx tried to send with from=<invalid@invalid>, but no impersonation permission given.
Feb 06 19:36:11 mx01 zcore[28204]: ZRPC FAIL 80070005h  1298µs SUBMITMESSAGE
Feb 06 19:36:11 mx01 zcore[28204]: I-1334: uid robin@xxx.xxx.xxx tried to send with from=<invalid@invalid>, but no impersonation permission given.
Feb 06 19:36:11 mx01 zcore[28204]: ZRPC FAIL 80070005h  1263µs SUBMITMESSAGE
Feb 06 19:36:12 mx01 zcore[28204]: I-1334: uid robin@xxx.xxx.xxx tried to send with from=<invalid@invalid>, but no impersonation permission given.
Feb 06 19:36:12 mx01 zcore[28204]: ZRPC FAIL 80070005h  1029µs SUBMITMESSAGE
Feb 06 19:36:12 mx01 zcore[28204]: I-1334: uid robin@xxx.xxx.xxx tried to send with from=<invalid@invalid>, but no impersonation permission given.
Feb 06 19:36:12 mx01 zcore[28204]: ZRPC FAIL 80070005h   950µs SUBMITMESSAGE
Feb 06 19:36:13 mx01 zcore[28204]: I-1334: uid robin@xxx.xxx.xxx tried to send with from=<invalid@invalid>, but no impersonation permission given.
Feb 06 19:36:13 mx01 zcore[28204]: ZRPC FAIL 80070005h 11570µs SUBMITMESSAGE

**Comment by amaccuish** [comment]
In the web interface, the messages are showing in the Outbox
![image](https://user-images.githubusercontent.com/9434795/217059559-847bf15a-d90c-4c30-be8c-c91cf616c5ff.png)

Messages sent from the webapp send correctly

**Comment by amaccuish** [comment]
The registry is showing the correct username/email is configured, so it's not sending from the wrong alias
![image](https://user-images.githubusercontent.com/9434795/217060434-2bd8767b-0c65-4b37-b5b6-37b926804473.png)

**Comment by jengelh** [comment]
```
To: Andrew XXX [andrew@xxx.xxx.xxx](mailto:andrew@xxx.xxx.xxx),
Alex XXX [alex@xxx.xxx.xxx](mailto:alex@xxx.xxx.xxx)
From:
```

In my book, you're trying to impersonate the "empty user", to give the situation a name,

**Comment by amaccuish** [comment]
Sure, but that's not on purpose. In the Windows Mail app, the sender is not selectable. And it displays the correct address.

**Comment by amaccuish** [comment]
I note there is a workaround already for a situation like this in the code. If the from is empty, surely the user's primary address should be use, no?
![image](https://user-images.githubusercontent.com/9434795/217067084-a059fa27-3b8f-44bb-bccf-51cf6ff62264.png)

**Comment by amaccuish** [comment]
I tested on a fresh Win10 VM with the Mail app and could reproduce immediately. Seems to only affect emails sent to multiple recipients, messages to a single recipient have the FROM header set.
